Optimize OVAL ID replacement logic
canonical/oval-xml-feed-merge pull request #17
Opened 2024-01-02 14:26 UTC by Ankush-Pathak

Updated OVAL ID replacement logic to replace ID only in case it is a duplicate as supposed to the current implementation that generates new IDs for each ID in each file.

**Testing:**

Verified manually through random diff checks of merged XML generated with and without the changes. The input XML files had duplicate OVAL IDs.

**Performance:**
Runtime measured using `time`
Before optimization: 
```
378.33s user 1.17s system 562% cpu 1:07.44 total
```

After optimization: 
```
170.97s user 1.19s system 542% cpu 31.751 total
```

2024-01-03 15:32 UTC, toabctl requested changes
Can you describe **in the commit message(s)** **why** you need to change this?

2024-01-04 10:49 UTC, Ankush-Pathak commented
> Can you describe **in the commit message(s)** **why** you need to change this?

@toabctl I have updated the commit message, and also made minor updates to the changeset. Could you please review again?

2024-01-04 16:25 UTC, toabctl approved these changes

2024-01-04 16:29 UTC, philroche approved these changes

2024-01-04 16:56 UTC, merged